services:
  - type: web
    name: ai-utilities-backend
    env: python
    buildCommand: pip install -r backend/demo_requirements.txt
    startCommand: python backend/demo_server.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
      - key: PYTHONPATH
        value: /opt/render/project/src
